repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-yaml
        args: [--multi]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: >
          (?x)^(openshiftcli/keywords/__init__.py |
            openshiftcli/cliclient/__init__.py |
            openshiftcli/dataloader/__init__.py |
            openshiftcli/dataparser/__init__.py |
            openshiftcli/base/__init__.py |
            openshiftcli/outputformatter/__init__.py |
            openshiftcli/outputstreamer/__init__.py
            )$
  - repo: https://github.com/gklein/check_signoff
    rev: v1.0.5
    hooks:
      - id: check-signoff
        language_version: python3.8
