apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: bitnami/nginx:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
