apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: bitnami/nginx:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: bitnami/nginx:latest
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
