apiVersion: v1
kind: Service
metadata:
  name: my-service-1
  namespace: test-project-1
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-2
  namespace: test-project-1
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30011
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-1
  namespace: test-project-2
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30012
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-1
  namespace: test-project-3
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30013
