apiVersion: v1
kind: Service
metadata:
  name: my-service-1
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30009
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-2
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
