apiVersion: v1
kind: Pod
metadata:
  name: {{ name }}
  namespace: default
  labels:
    role: myrole
spec:
  containers:
    - name: container
      image: {{ image }}
      ports:
        - name: web
          containerPort: 80
          protocol: TCP